language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexandrelessard/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexandrelessard/react-test npm test -- --coverage

after_success:
  - docker build -t alexandrelessard/multi-client ./client
  - docker build -t alexandrelessard/multi-nginx ./nginx
  - docker build -t alexandrelessard/multi-server ./server
  - docker build -t alexandrelessard/multi-worker ./worker
